### ISSUE TITLE
Test: numberToChinese

### ISSUE THREAD

**Issue by icctuan** [nryz-fe/yz-utils#2]
### Steps to reproduce
```js
const o = numberToChinese(20)
console.log(o)
```
### What is expected?
```js
console.log(o)  // 贰拾元整
```

### What is actually happening?
```js
console.log(o)  // 零贰拾元整
```

## Perf
~~1. 根据代码逻辑，decimal不为0的情况下，first和second一定有值，以下三元判断符无效：~~
```diff
- 65  decimal_result += first ? tlist[first] + unitList[1] : ''
- 66  decimal_result += second ? tlist[second] + unitList[2] : ''
```
2. 根据代码逻辑， 内部函数_getStr的参数n没有 === 0 的情况，调用该函数的所有分支，在调用之前都有判断>=1
```diff
- 31  if (n === 0) resultStrList.unshift(tlist[0])
```

**Comment by 962464zyy** [comment]
这里的两行三元运算符不是针对 first和second 两个变量是否有值的判断，而是判断 0 和 1、2、3、4、5、6、7、8、9

**Comment by icctuan** [comment]
> 这里的两行三元运算符不是针对 first和second 两个变量是否有值的判断，而是判断 0 和 1、2、3、4、5、6、7、8、9

我表达的是一个意思，你用的if判断，这里两个变量的逻辑永远不会===0，所以三元运算符无意义，如果我漏了哪个条件，你可以举例。

**Comment by 962464zyy** [comment]
`
  const _getInteger = (num) => {
	  return num >= 0 ? Math.floor(num) : Math.ceil(num)
  }
  const decimal = 0.01
  const first = _getInteger(decimal * 10) % 10   // 0
  const second = _getInteger(decimal * 100) % 10 // 1
  decimal_result += first ? tlist[first] + unitList[1] : ''
  decimal_result += second ? tlist[second] + unitList[2] : ''
`
假设 decimal 值为 0.01 ,调用_getInteger(0.1)的结果是0，调用_getInteger(1)的结果是1

**Comment by icctuan** [comment]
> ```
>   const _getInteger = (num) => {
> 	  return num >= 0 ? Math.floor(num) : Math.ceil(num)
>   }
>   const decimal = 0.01
>   const first = _getInteger(decimal * 10) % 10   // 0
>   const second = _getInteger(decimal * 100) % 10 // 1
>   decimal_result += first ? tlist[first] + unitList[1] : ''
>   decimal_result += second ? tlist[second] + unitList[2] : ''
> ```
> 
> 假设 decimal 值为 0.01 ,调用_getInteger(0.1)的结果是0，调用_getInteger(1)的结果是1

又看了一遍，感觉是因为[issue3](https://github.com/nryz-fe/yz-utils/issues/3)的问题导致的代码测试无法覆盖，这个perf1可以不用看了，新增了perf2看一下。

**Comment by thomas-void0** [comment]
> > ```
> >   const _getInteger = (num) => {
> > 	  return num >= 0 ? Math.floor(num) : Math.ceil(num)
> >   }
> >   const decimal = 0.01
> >   const first = _getInteger(decimal * 10) % 10   // 0
> >   const second = _getInteger(decimal * 100) % 10 // 1
> >   decimal_result += first ? tlist[first] + unitList[1] : ''
> >   decimal_result += second ? tlist[second] + unitList[2] : ''
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 假设 decimal 值为 0.01 ,调用_getInteger(0.1)的结果是0，调用_getInteger(1)的结果是1
> 
> 又看了一遍，感觉是因为[issue3](https://github.com/nryz-fe/yz-utils/issues/3)的问题导致的代码测试无法覆盖，这个perf1可以不用看了，新增了perf2看一下。

对此，我的建议是：劳逸结合
